# Análise de Dados em Python 
**Professor Responsável:** Antonio Sergio Ferreira Bonato <antonio.bonato@saojudas.br>

# <font color='red'>Solução</font> da Atividade03 - NumPy Básico: Arrays e Processamento Vetorizado

**Conteúdo:**
- O que é NumPy; NumPy arrays; operações com arrays
- NumPy: matrizes e operações com matrizes
- NumPy: carregando dados com NumPy
- NumPy: álgebra linear básica

## Exercícios

**1** Utilize o código dado para importar o arquivo `dados.csv`, que contém dados de saúde sobre homens e mulheres de diversas idades. Veja na tabela a descrição dos campos.

|Ordem|Campo|Descrição|
|:-|:-|:-|
|0|sexo|Homem=0 Mulher=1|
|1|idade|anos completos|
|2|rendom|renda domiciliar|
|3|anoest|anos de estudo|
|4|altura||
|5|peso||
|6|probagud|0 não teve problemas nos últimos 30 dias, 1 = teve problema nos últimos 30 dias|
|7|probcron|0 não tem problemas crônicos, 1 = tem problemas crônicos|
|8|gastorem|gasto com medicamentos nos últimos 30 dias|

Utilize o código pronto para importar os dados. Veja que o parâmetro `converters` da função `loadtxt` contém um dicionário que converte os dados faltantes para `nan` (not a number).

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import numpy as np

headers = np.array(['sexo', 'idade', 'rendom', 'anoest', 'altura', 'peso', 'probagud', 'probracron', 'gastorem'])
zera = lambda x: np.nan if len(x)==0 else x
conversores = {i:zera for i in range(9)}
path = '/content/drive/MyDrive/2022_2_extensao_adp/'
arr = np.loadtxt(path+'aula03_dados.csv', delimiter=';',dtype=np.float64, converters=conversores)

**a)** Imprima o formato do array arr.

In [ ]:
#solução
arr.shape

(3897, 9)

**b)** Imprima as 10 primeiras linhas do vetor e examine-as.

In [ ]:
#solução
arr[:10]

array([[0.000e+00, 4.000e+00, 1.320e+02, 1.000e+00, 9.600e-01, 1.500e+01,
        1.000e+00, 1.000e+00, 4.600e+00],
       [0.000e+00, 5.000e+01, 1.089e+03, 1.000e+00, 1.690e+00, 5.400e+01,
        1.000e+00, 0.000e+00, 4.250e+00],
       [0.000e+00, 1.100e+01, 1.570e+02, 2.000e+00, 1.320e+00, 2.700e+01,
        1.000e+00, 0.000e+00, 5.000e+00],
       [0.000e+00, 2.000e+00, 1.570e+02, 1.000e+00,       nan, 1.300e+01,
        1.000e+00, 0.000e+00, 5.000e+00],
       [0.000e+00, 1.000e+01, 3.000e+02, 3.000e+00, 1.360e+00, 4.300e+01,
        1.000e+00, 0.000e+00, 2.000e+00],
       [0.000e+00, 1.000e+00, 9.410e+02, 1.000e+00, 8.500e-01, 1.400e+01,
        1.000e+00, 0.000e+00, 4.000e-01],
       [0.000e+00, 5.500e+01, 7.520e+02, 1.000e+00, 1.570e+00, 5.400e+01,
        1.000e+00, 1.000e+00, 7.000e-01],
       [0.000e+00, 1.700e+01, 7.520e+02, 1.000e+00, 1.560e+00, 4.600e+01,
        1.000e+00, 0.000e+00, 2.500e-01],
       [0.000e+00, 4.800e+01, 2.080e+02, 1.000e+00, 1.610e+00, 5.800e+01

**c)** Verifique se há colunas com dados nan. Quais são as colunas? Dicas: use o array headers definido no código dado, a ufunction `isnan()` e a função `any()`, um loop `for` e indexação booleana.

In [ ]:
#solução
for header in headers:
    print(header, np.any(np.isnan(arr[:,headers==header])))

sexo False
idade False
rendom False
anoest False
altura True
peso True
probagud False
probracron False
gastorem False


**d)** Crie uma visão do array arr sem as linhas que contém anotações faltantes (dados nan).

In [ ]:
print(arr[~np.isnan(arr[:,4])].shape)
print(arr[~np.isnan(arr[:,5])].shape)
not_nan = arr[~(np.isnan(arr[:,4]) | np.isnan(arr[:,5]))]
print(not_nan.shape)

(3580, 9)
(3606, 9)
(3570, 9)


**e)** Calcule a média de cada coluna da visão not_nan e atribua aos nan da coluna altura a média da altura e aos nan da coluna peso a média da coluna peso. Antes da trocar os nan, calcule a média das colunas de arr para ver o que acontece.

Lembre-se de como funcionam os eixos! Abaixo um exemplo com a função `sum()`
![eixos.svg](attachment:eixos.svg)

In [ ]:
print('média das colunas de arr', np.mean(arr, axis=0))
m_altura, m_peso = np.mean(not_nan, axis=0)[4:6]
print('média de altura', m_altura)
print('média do peso', m_peso)

#consertando a altura
arr[np.isnan(arr[:,4]), 4] = m_altura
#consertando o peso
arr[np.isnan(arr[:,5]), 5] = m_peso

média das colunas de arr [5.81472928e-01 3.57282525e+01 1.67612779e+03 5.60020529e+00
            nan            nan 5.59917886e-01 3.84141647e-01
 3.19301976e+01]
média de altura 1.494226890756314
média do peso 54.8703081232493


In [ ]:
arr[np.isnan(arr[:,4])]
arr[np.isnan(arr[:,5])]

array([], shape=(0, 9), dtype=float64)

**f)** calcule agora a média, o desvio padrão, o máximo e o mínimo de todas as colunas do array sem filtro

In [ ]:
print('médias', arr.mean(0))
print('desvios padrão', arr.std(0))
print('máximo', arr.max(0))
print('mínimo', arr.min(0))

médias [5.81472928e-01 3.57282525e+01 1.67612779e+03 5.60020529e+00
 1.49434948e+00 5.47157454e+01 5.59917886e-01 3.84141647e-01
 3.19301976e+01]
desvios padrão [4.93317506e-01 2.34012167e+01 2.67240290e+03 4.57686386e+00
 2.63920735e-01 2.18949249e+01 4.96396864e-01 4.86391655e-01
 1.31164111e+02]
máximo [1.0000e+00 9.6000e+01 4.1484e+04 1.7000e+01 1.9900e+00 1.4500e+02
 1.0000e+00 1.0000e+00 7.0000e+03]
mínimo [0.   0.   0.   0.   0.43 3.   0.   0.   0.  ]


**2** Escreva duas funções, `get_rows` e `get_columns`, que recebem um array bidimensional como parâmetro. Elas devem retornar uma lista de linhas e colunas do array, respectivamente. As linhas e colunas devem ser matrizes unidimensionais. Você pode usar a operação de transposição, que inverte linhas para colunas, em sua solução. A transposição é feita pelo método `T`.

In [ ]:
#exemplo
a=np.random.randint(0, 10, (4,4))
print(a)
print(a.T)

[[3 6 1 9]
 [7 9 3 5]
 [6 9 4 0]
 [1 5 8 3]]
[[3 7 6 1]
 [6 9 9 5]
 [1 3 4 8]
 [9 5 0 3]]


In [ ]:
#solução
def get_rows(m):
    return [row for row in m]

In [ ]:
#solução
def get_columns(m):
    m = m.T
    return get_rows(m)

In [ ]:
#teste - dados
a = np.array([[5, 0, 3, 3],
              [7, 9, 3, 5],
              [2, 4, 7, 6],
              [8, 8, 1, 6]])

In [ ]:
#teste row
print(get_rows(a))
#[array([5, 0, 3, 3]), array([7, 9, 3, 5]), array([2, 4, 7, 6]), array([8, 8, 1, 6])]

[array([5, 0, 3, 3]), array([7, 9, 3, 5]), array([2, 4, 7, 6]), array([8, 8, 1, 6])]


In [ ]:
#teste column
print(get_columns(a))
#[array([5, 7, 2, 8]), array([0, 9, 4, 8]), array([3, 3, 7, 1]), array([3, 5, 6, 6])]

[array([5, 7, 2, 8]), array([0, 9, 4, 8]), array([3, 3, 7, 1]), array([3, 5, 6, 6])]


**3** Crie a função `get_row_vectors` que retorna uma lista de linhas do array de entrada da forma `(n, m)`, mas desta vez as linhas devem ter a forma `(1, m)`. Da mesma forma, crie a função get_columns_vectors que retorne uma lista de colunas (cada uma com forma `(n, 1)`) da matriz de entrada.

Para a entrada:

`[[5 0 3]
 [3 7 9]]`
 
Deve ser gerada a saída:

Vetor de Linhas:

`[array([[5, 0, 3]]), array([[3, 7, 9]])]`

Vetor de Colunas:

`[array([[5],
        [3]]),
 array([[0],
        [7]]),
 array([[3],
        [9]])]`

In [ ]:
#solucao row
def get_row_vectors(m):
    return [row.reshape(1,m.shape[1]) for row in m]

In [ ]:
#solucao column
def get_column_vectors(m):
    m = m.T
    return [row.reshape(m.shape[1],1) for row in m]

In [ ]:
#teste - dados
a = np.array([[5, 0, 3],[3, 7, 9]])
a.shape

(2, 3)

In [ ]:
#teste row
print(get_row_vectors(a))

[array([[5, 0, 3]]), array([[3, 7, 9]])]


In [ ]:
#test column
print(get_column_vectors(a))

[array([[5],
       [3]]), array([[0],
       [7]]), array([[3],
       [9]])]


**4** Crie a função `diamante` que retorne um array inteiro bidimensional em que os 1s formem uma forma de diamante. O restante dos números é 0. A função deve receber um parâmetro que informe o comprimento de um lado do diamante. Faça isso usando as funções `eye` e `concatenate` do NumPy e o fatiamento de array.

Ex:

`print(diamante(3))`

`[[0 0 1 0 0]
 [0 1 0 1 0]
 [1 0 0 0 1]
 [0 1 0 1 0]
 [0 0 1 0 0]]`

`print(diamante(1))`

`[[1]]`

In [ ]:
#Exemplo do concatenate
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#Exemplo do concatenate
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
#Exemplo do concatenate
np.concatenate((a, b), axis=None)

array([1, 2, 3, 4, 5, 6])

In [ ]:
#solução
def diamante(n):
    arr = np.eye(n,dtype=np.int)
    arr1 = np.concatenate((arr,arr[:,1:][::-1]), axis=1)
    arr2 = np.concatenate((arr1[1:,:][::-1],arr1), axis=0)
    return arr2

In [ ]:
#teste
print(diamante(3))

[[0 0 1 0 0]
 [0 1 0 1 0]
 [1 0 0 0 1]
 [0 1 0 1 0]
 [0 0 1 0 0]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  This is separate from the ipykernel package so we can avoid doing imports until


In [ ]:
#teste
print(diamante(1))

[[1]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  This is separate from the ipykernel package so we can avoid doing imports until


**5** Escreva a função lambda `so_pares` que receba um array unidimensional de inteiros e devolva este array sem números ímpares. Dica: use indexação booleana.

Ex:

Entrada: 

`arr = np.array([0,1,2,3,4,5,6,7,8,9])`

Saída:

`array([0, 2, 4, 6, 8])`

In [ ]:
#solucao
so_pares = lambda arr: arr[arr%2==0]

In [ ]:
#teste
arr = np.arange(10)
so_pares(arr)

array([0, 2, 4, 6, 8])

**6** Escreva a função lambda `cade_os_iguais` que receba dois arrays unidimensionais de inteiros x e y e devolva um array com a(s) posição(ões) em que há números iguais nos dos arrays. Não use `for`. Dica: use np.where

Ex:

Entrada: 

`x = np.array([5,6,7,8,3,4])`

`y = np.array([5,3,4,5,2,4])`

Saída:

`array([0, 5])`

In [ ]:
#solucao
cade_os_iguais = lambda x,y: np.where(x == y)

In [ ]:
#teste
x = np.array([5,6,7,8,3,4])
y = np.array([5,3,4,5,2,4])
cade_os_iguais(x,y)

(array([0, 5]),)