# Análise de Dados em Python 
**Professor Responsável:** Antonio Sergio Ferreira Bonato <antonio.bonato@saojudas.br>

# Atividade03 - NumPy Básico: Arrays e Processamento Vetorizado

**Conteúdo:**
- O que é NumPy; NumPy arrays; operações com arrays
- NumPy: matrizes e operações com matrizes
- NumPy: carregando dados com NumPy
- NumPy: álgebra linear básica

In [ ]:
import numpy as np

## Exercícios

**1** Utilize o código dado para importar o arquivo `dados.csv`, que contém dados de saúde sobre homens e mulheres de diversas idades. Veja na tabela a descrição dos campos.

|Ordem|Campo|Descrição|
|:-|:-|:-|
|0|sexo|Homem=0 Mulher=1|
|1|idade|anos completos|
|2|rendom|renda domiciliar|
|3|anoest|anos de estudo|
|4|altura||
|5|peso||
|6|probagud|0 não teve problemas nos últimos 30 dias, 1 = teve problema nos últimos 30 dias|
|7|probcron|0 não tem problemas crônicos, 1 = tem problemas crônicos|
|8|gastorem|gasto com medicamentos nos últimos 30 dias|

Utilize o código pronto para importar os dados. Veja que o parâmetro `converters` da função `loadtxt` contém um dicionário que converte os dados faltantes para `nan` (not a number).

In [ ]:
zera = lambda x: np.nan if len(x)==0 else x

In [ ]:
conversores = {i:zera for i in range(9)}
conversores

{0: <function __main__.<lambda>(x)>,
 1: <function __main__.<lambda>(x)>,
 2: <function __main__.<lambda>(x)>,
 3: <function __main__.<lambda>(x)>,
 4: <function __main__.<lambda>(x)>,
 5: <function __main__.<lambda>(x)>,
 6: <function __main__.<lambda>(x)>,
 7: <function __main__.<lambda>(x)>,
 8: <function __main__.<lambda>(x)>}

In [ ]:
zera('')

nan

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
path = '/content/drive/MyDrive/2022_2_extensao_adp/'
arr = np.loadtxt(path+'aula03_dados.csv', delimiter=';',dtype=np.float64, converters=conversores)

In [ ]:
headers = np.array(['sexo', 'idade', 'rendom', 'anoest', 'altura', 'peso', 'probagud',
                   'probcron', 'gastorem'])
headers

**a)** Imprima o formato do array arr.

In [ ]:
#solucao

**b)** Imprima as 10 primeiras linhas do vetor e examine-as.

In [ ]:
#solucao

**c)** Verifique se há colunas com dados nan. Quais são as colunas? Dicas: use o array headers definido no código dado, a ufunction `isnan()` e a função `any()`, um loop `for` e indexação booleana.

In [ ]:
#solucao

**d)** Crie uma visão do array arr sem as linhas que contém anotações faltantes (dados nan).

In [ ]:
#solucao

**e)** Calcule a média de cada coluna da visão not_nan e atribua aos nan da coluna altura a média da altura e aos nan da coluna peso a média da coluna peso. Antes da trocar os nan, calcule a média das colunas de arr para ver o que acontece. 

Lembre-se de como funcionam os eixos! Abaixo um exemplo com a função `sum()`
![eixos](https://saskeli.github.io/data-analysis-with-python-summer-2019/_images/aggregation.svg)

In [ ]:
#solução

**f)** calcule agora a média, o desvio padrão, o máximo e o mínimo de todas as colunas do array sem filtro

In [ ]:
#solução

**2** Escreva duas funções, `get_rows` e `get_columns`, que recebem um array bidimensional como parâmetro. Elas devem retornar uma lista de linhas e colunas do array, respectivamente. As linhas e colunas devem ser matrizes unidimensionais. Você pode usar a operação de transposição, que inverte linhas para colunas, em sua solução. A transposição é feita pelo método `T`.

In [ ]:
#exemplo
a=np.random.randint(0, 10, (4,4))
print(a)
print(a.T)

In [ ]:
#solução

In [ ]:
#solução

In [ ]:
#teste - dados
a = np.array([[5, 0, 3, 3],
              [7, 9, 3, 5],
              [2, 4, 7, 6],
              [8, 8, 1, 6]])

In [ ]:
#teste row
print(get_rows(a))
#[array([5, 0, 3, 3]), array([7, 9, 3, 5]), array([2, 4, 7, 6]), array([8, 8, 1, 6])]

In [ ]:
#teste column
print(get_columns(a))
#[array([5, 7, 2, 8]), array([0, 9, 4, 8]), array([3, 3, 7, 1]), array([3, 5, 6, 6])]

**3** Crie a função `get_row_vectors` que retorna uma lista de linhas do array de entrada da forma `(n, m)`, mas desta vez as linhas devem ter a forma `(1, m)`. Da mesma forma, crie a função get_columns_vectors que retorne uma lista de colunas (cada uma com forma `(n, 1)`) da matriz de entrada.

Para a entrada:

`[[5 0 3]
 [3 7 9]]`
 
Deve ser gerada a saída:

Vetor de Linhas:

`[array([[5, 0, 3]]), array([[3, 7, 9]])]`

Vetor de Colunas:

`[array([[5],
        [3]]),
 array([[0],
        [7]]),
 array([[3],
        [9]])]`

In [ ]:
#solucao row
def get_row_vectors(m):
    return []

In [ ]:
#solucao column
def get_column_vectors(m):
    m = m.T
    return []

In [ ]:
#teste - dados
a = np.array([[5, 0, 3],[3, 7, 9]])
a.shape

In [ ]:
#teste row
print(get_row_vectors(a))

In [ ]:
#test column
print(get_column_vectors(a))

**4** Crie a função `diamante` que retorne um array inteiro bidimensional em que os 1s formem uma forma de diamante. O restante dos números é 0. A função deve receber um parâmetro que informe o comprimento de um lado do diamante. Faça isso usando as funções `eye` e `concatenate` do NumPy e o fatiamento de array.

Ex:

`print(diamante(3))`

`[[0 0 1 0 0]
 [0 1 0 1 0]
 [1 0 0 0 1]
 [0 1 0 1 0]
 [0 0 1 0 0]]`

`print(diamante(1))`

`[[1]]`

In [ ]:
#Exemplo do concatenate
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

In [ ]:
#Exemplo do concatenate
np.concatenate((a, b.T), axis=1)

In [ ]:
#Exemplo do concatenate
np.concatenate((a, b), axis=None)

In [ ]:
#solução
def diamante(n):
    pass

In [ ]:
#teste
print(diamante(3))

In [ ]:
#teste
print(diamante(1))

**5** Escreva a função lambda `so_pares` que receba um array unidimensional de inteiros e devolva este array sem números ímpares. Dica: use indexação booleana.

Ex:

Entrada: 

`arr = np.array([0,1,2,3,4,5,6,7,8,9])`

Saída:

`array([0, 2, 4, 6, 8])`

In [ ]:
#solucao

In [ ]:
#teste
arr = np.arange(10)

**6** Escreva a função lambda `cade_os_iguais` que receba dois arrays unidimensionais de inteiros x e y e devolva um array com a(s) posição(ões) em que há números iguais nos dos arrays. Não use `for`. Dica: use np.where

Ex:

Entrada: 

`x = np.array([5,6,7,8,3,4])`

`y = np.array([5,3,4,5,2,4])`

Saída:

`array([0, 5])`

In [ ]:
#solucao

In [ ]:
#teste
x = np.array([5,6,7,8,3,4])
y = np.array([5,3,4,5,2,4])